### ISSUE TITLE
Missing legendary ring Manald Heal

### ISSUE THREAD

**Issue by MathewBlock** [Raylehnhoff/Have-I-Cubed-This-Yet#14]
Manald Heal was given a legendary affix in 2.4.3, could you add this item?
http://diablo.wikia.com/wiki/Manald_Heal_(Diablo_III)

**Comment by Raylehnhoff** [comment]
Hi,

I haven't updated this in several patches and really have no intention to, as my focus has moved to other (monetized) projects.

I'd be happy to accept pull requests, but I just don't really want to devote effort to this tool, especially since in-game cube notifications have been added since the project launched, as well as Turbo HUD having pretty good support for whether items have been cubed or not for those willing to take the risk to use it.

**Comment by MathewBlock** [comment]
Thanks getting back to me and I totally understand.

For now I've just added the item in by exporting my data, adding the item, then importing it back in. If I manage to roll up my sleeves and make some changes I'll submit some pull requests.

Cheers.
